steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/gcp-lab-p1/cd-devops-repo/flask-app',
      '.'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'flask-app',
      '--image', 'asia-south1-docker.pkg.dev/gcp-lab-p1/cd-devops-repo/flask-app',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-south1-docker.pkg.dev/gcp-lab-p1/cd-devops-repo/flask-app'

